CREATE TABLE [cass].[t_dim_Типы_касс]
(
	[Код_типа_кассы] NVARCHAR(7) NOT NULL, 
    [Наименование] NVARCHAR(30) NOT NULL,
	CONSTRAINT [PK_t_dim_Типы_касс] PRIMARY KEY CLUSTERED
	([Код_типа_кассы] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [DIMENTIONS]
) ON [DIMENTIONS];
