CREATE TABLE [cass].[t_raw_fsk_Смены] (
    [ИД_смены]                         INT          NOT NULL,
    [Номер_смены]                      INT          NOT NULL,
    [Код_кассира]                      VARCHAR (30) NOT NULL,
    [Дата_время_начала_смены]          DATETIME     NOT NULL,
    [Дата_время_окончания_смены]       DATETIME     NULL,
    [Номер_первого_чека_в_смене]       INT          NOT NULL,
    [Номер_последнего_чека_в_смене]    INT          NOT NULL,
    [Сумма_продажи]                    MONEY        NOT NULL,
    [Сумма_выручки]                    MONEY        NOT NULL,
    [Сумма_в_денежном_ящике]           MONEY        NOT NULL,
    [Признак_изменения_данных]         BIT          NOT NULL,
    [Дата_время_открытия_первого_чека] DATETIME     NOT NULL,
    [Сумма_продажи_наличные]           MONEY        NOT NULL,
    [Сумма_продажи_безналичные]        MONEY        NOT NULL,
    [Сумма_продажи_прочие]             MONEY        NOT NULL,
    [Сумма_выручки_наличные]           MONEY        NOT NULL,
    [Сумма_выручки_безналичные]        MONEY        NOT NULL,
    [Сумма_возвратов]                  MONEY        NOT NULL,
    [Сумма_возвратов_наличные]         MONEY        NOT NULL,
    [Сумма_возвратов_безналичные]      MONEY        NOT NULL,
    [Количество_чеков_продажи]         INT          NOT NULL,
    [Количество_чеков_возврата]        INT          NOT NULL
) ON [RAW];

